---
- name: configure instance ansible development workstation
  hosts: "{{ target_hosts }}"

  tasks:
    - name: install ansible-navigator
      ansible.builtin.yum: 

    - name: install ansible-builder
      ansible.builtin.yum

  
# yum install python3 -y
# pip3 install ansible-builder
# yum module install -y container-tools

# python3 -m pip install ansible-navigator —user
# echo ‘export PATH=$HOME/.local/bin:$PATH’ >> ~/.profile
# source ~/.profile
# ansible-navigator
# yum install -y rhel-system-roles